# Scalable Render configuration for the document catalog application
databases:
  - name: document-catalog-db
    region: oregon

services:
  # Redis instance for Celery
  - type: redis
    name: redis
    region: oregon
    plan: free
    ipAllowList: []

  # Main FastAPI Application
  - type: web
    name: document-catalog-app
    env: python
    region: oregon
    plan: standard
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/health"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENVIRONMENT
        value: "production"
      - key: DATABASE_URL
        fromDatabase:
          name: document-catalog-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: STORAGE_TYPE
        value: "s3"
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ENDPOINT_URL
        sync: false

  # Celery Background Worker
  - type: worker
    name: celery-worker
    env: python
    region: oregon
    plan: standard
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: "celery -A worker.celery_app worker --loglevel=info --concurrency=2"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENVIRONMENT
        value: "production"
      - key: DATABASE_URL
        fromDatabase:
          name: document-catalog-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: SECRET_KEY
        fromService:
          type: web
          name: document-catalog-app
          envVarKey: SECRET_KEY
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: STORAGE_TYPE
        value: "s3"
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ENDPOINT_URL
        sync: false
