"""Create document_taxonomy_map table
Revision ID: 183fbe27b9bb
Revises: 97f28fa6d77c
Create Date: 2025-08-05 17:03:51.943771
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision: str = "183fbe27b9bb"
down_revision: Union[str, None] = "97f28fa6d77c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name):
    bind = op.get_bind()
    if bind is None:
        return False
    inspector = reflection.Inspector.from_engine(bind)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists("document_taxonomy_map"):
        op.create_table(
            "document_taxonomy_map",
            sa.Column("document_id", sa.Integer(), nullable=False),
            sa.Column("taxonomy_term_id", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["document_id"],
                ["documents.id"],
            ),
            sa.ForeignKeyConstraint(
                ["taxonomy_term_id"],
                ["taxonomy_terms.id"],
            ),
            sa.PrimaryKeyConstraint("document_id", "taxonomy_term_id"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists("document_taxonomy_map"):
        op.drop_table("document_taxonomy_map")
    # ### end Alembic commands ###
