"""recreate_document_taxonomy_map_table

Revision ID: 76ce7437e49a
Revises: 183fbe27b9bb
Create Date: 2025-08-06 12:41:24.438923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76ce7437e49a"
down_revision: Union[str, None] = "183fbe27b9bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_taxonomy_map")
    op.create_table(
        "document_taxonomy_map",
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("taxonomy_term_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_term_id"],
            ["taxonomy_terms.id"],
        ),
        sa.PrimaryKeyConstraint("document_id", "taxonomy_term_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_taxonomy_map")
    op.create_table(
        "document_taxonomy_map",
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("taxonomy_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "taxonomy_term_id", sa.Integer(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name="document_taxonomy_map_document_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "document_id",
            "taxonomy_id",
            "taxonomy_term_id",
            name="document_taxonomy_map_pkey",
        ),
    )
    # ### end Alembic commands ###
